"use client";
/* import type { Metadata } from "next";
 */ import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box, Container } from "@mui/material";
import Navbar from "@/components/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
          <div>
            <Navbar />

            <Container maxWidth="xl">
              <Box sx={{ mt: "5.5rem" }}>{children}</Box>
            </Container>
          </div>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
